sudo: required
services:
  - docker

before_install:
  - docker build -t rnarukulla2/docker_multi -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rnarukulla2/docker_multi npm test

after_success:
  - docker build -t rnarukulla/multi-client ./client
  - docker build -t rnarukulla/multi-nginx ./nginx
  - docker build -t rnarukulla/multi-server ./server
  - docker build -t rnarukulla/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rnarukulla/multi-client
  - docker push rnarukulla/multi-nginx
  - docker push rnarukulla/multi-server
  - docker push rnarukulla/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-south-1
  app: docker_multi
  env: DockerMulti-env
  bucket_name: elasticbeanstalk-ap-south-1-784341780032
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
